# Используем официальное Node.js изображение как базовое
FROM node:18

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /Users/valtzmanmagnus/Desktop/TASK_APPLICATION/FRONT

# Копируем файл package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта в контейнер
COPY . .

# Собираем приложение для продакшена
RUN npm run build

# Устанавливаем Nginx для раздачи собранных файлов
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Открываем порт 80
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]